Repository varvet/pundit, pull requests merged in 2018-05, with the labels that each got.

#392 Add documentation for namespace support; resolves #373
  README.md
Labels: documentation

#409 Add docs for closed system scopes
  README.md
Labels: documentation

#461 Fix code examples in Scopes section
  README.md
Labels: documentation

#462 Error message when constructor called wrongly
  lib/pundit.rb
  spec/pundit_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#516 Improve policy generator
  lib/generators/pundit/install/install_generator.rb
  lib/generators/pundit/policy/policy_generator.rb
  lib/generators/pundit/policy/templates/policy.rb
  lib/generators/rspec/policy_generator.rb
  lib/generators/rspec/templates/policy_spec.rb
  lib/generators/test_unit/policy_generator.rb
  lib/generators/test_unit/templates/policy_test.rb
Labels: enhancement

#475 fix PolicyFinder when given an array with policy class override
  lib/pundit/policy_finder.rb
  spec/pundit_spec.rb
  spec/spec_helper.rb
Labels: bug

#488 Use `.all` in generated policy scopes
  lib/generators/pundit/install/templates/application_policy.rb
  lib/generators/pundit/policy/templates/policy.rb
  spec/pundit_spec.rb
  spec/spec_helper.rb
Labels: enhancement
